Support websocket server in docker
hashgraph/hedera-json-rpc-relay pull request #1168
Opened 2023-05-02 10:01 UTC by isavov

**Description**:

**Related issue(s)**:

Fixes #1166 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-13 04:35 UTC, Nana-EC requested changes
A few suggestions.
I think we should consider a separate chart for this to allow simpler maintenance (each chart only has what it needs) and easier understanding of how each scales together.

Another chart under a `/charts` dir similar to PR 1242 is what i'm thinking.

2023-05-13 04:35 UTC, Nana-EC commented on helm-chart/ci/default-values.yaml
> +  CHAIN_ID: "0x128"
Q: why to double quotes?
Revert if it was accidental for consistency

2023-05-13 04:35 UTC, Nana-EC commented on helm-chart/ci/default-values.yaml
> +    cpu: 550m
Q" Is this still needed with the recent Helm chart update?

2023-05-13 04:35 UTC, Nana-EC commented on helm-chart/templates/configmap.yaml
> +  WS_MAX_CONNECTION_TTL: {{ .Values.config.WS_MAX_CONNECTION_TTL | quote }}
nit: preserve newline at end of file

2023-05-13 04:35 UTC, Nana-EC commented on .env.example
> +ETH_FEE_HISTORY_FIXED=
nit: preserve newline at end of file

2023-05-13 04:35 UTC, Nana-EC commented on Dockerfile
> +CMD ["start"]
nit: preserve newline at end of file

2023-05-13 04:35 UTC, Nana-EC commented on helm-chart/templates/deployment.yaml
> +    app:  {{ template "json-rpc-relay.name" . }}-websocket
define a `json-rpc-relay.wsname` in the `_helpers.tpl` so you don't have to keep doing this.

2023-05-13 04:35 UTC, Nana-EC commented on helm-chart/templates/deployment.yaml
> +            name: {{ include "json-rpc-relay.fullname" . }}
Does this mean the JSON RPC API and the websocket deployment share the same config? SHouldn't they be different?
I'm wondering if instead we should have a separate chart?

2023-05-13 04:35 UTC, Nana-EC requested changes
A few suggestions.
I think we should consider a separate chart for this to allow simpler maintenance (each chart only has what it needs) and easier understanding of how each scales together.

Another chart under a `/charts` dir similar to PR 1242 is what i'm thinking.

2023-05-13 07:15 UTC, isavov commented
> A few suggestions. I think we should consider a separate chart for this to allow simpler maintenance (each chart only has what it needs) and easier understanding of how each scales together.
> 
> Another chart under a `/charts` dir similar to PR 1242 is what i'm thinking.

Thanks! I was thinking of something similar as mentioned in the Notes for reviewer section, and in light of #1242  and the changes it makes I'll rework this PR to address only the docker and docker-compose changes needed for websocket and create a separate chart in a new PR after #1242 is merged.

2023-05-15 17:50 UTC, Nana-EC approved these changes

2023-05-15 20:02 UTC, AlfredoG87 approved these changes
LGTM  👍

2023-05-16 03:21 UTC, merged

2023-05-24 18:48 UTC, Nana-EC commented
@isavov #1253 is merged so you can add a new deployment resource for the `eth_subcribe` server