Reapplying refactor/enhancement in a fresh branch off of main since t…
hashgraph/hedera-json-rpc-relay pull request #1186
Opened 2023-05-04 22:59 UTC by ebadiere

…… (#1164)

This PR optimizes the getBalance method by removing unnecessary calls to the mirror node.

Optimizes eth_getBalance.

**Related issue(s)**:

Fixes #1085

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-04 23:15 UTC, Nana-EC submitted a review, later dismissed

2023-05-05 00:10 UTC, Nana-EC requested changes
DCO failing

2023-05-05 00:30 UTC, lukelee-sl submitted a review, later dismissed

2023-05-05 00:37 UTC, AlfredoG87 commented
DCO Failing

2023-05-05 00:42 UTC, Nana-EC approved these changes

2023-05-05 01:16 UTC, merged