Fix flaky acceptance tests
hashgraph/hedera-json-rpc-relay pull request #1255
Opened 2023-05-16 14:15 UTC by Ivo-Yankov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-28 03:03 UTC, Nana-EC requested changes
Nice improvements.
I would prefer the ContractID on the Token instead. If that will be a large lift then let's consider an immediate follow up PR to resolve that, but if doable let's update this PR with that approach.

2023-05-28 03:03 UTC, Nana-EC commented on packages/server/tests/clients/servicesClient.ts
> +    async createAccountWithContractIdKey(contractIdString: string, initialBalance = 10, provider = null, requestId?: string) {
I think the better approach would be to have the token.key hold the contract ID
e.g. to authorize Contract A to freeze/unfreeze Token T, then T.freezeKey should be set to ContractID A at token creation.

2023-05-29 11:42 UTC, Ivo-Yankov commented on packages/server/tests/localAcceptance.env
> +DEFAULT_RATE_LIMIT=200
Many of those env vars are marked as mandatory in the code. We should probably address this in a separate PR

2023-05-30 13:32 UTC, Nana-EC commented on packages/server/tests/clients/servicesClient.ts
> +    async createAccountWithContractIdKey(contractIdString: string, initialBalance = 10, provider = null, requestId?: string) {
Agreed in follow up PR to also utilize T.freezeKey = ContractID for increased coverage

2023-05-30 13:32 UTC, Nana-EC approved these changes

2023-05-30 17:34 UTC, ebadiere reviewed
LG

2023-05-30 17:52 UTC, AlfredoG87 approved these changes
LG

2023-05-30 19:19 UTC, ebadiere approved these changes

2023-05-30 22:23 UTC, Nana-EC approved these changes

2023-06-02 15:34 UTC, ebadiere reviewed
LG

2023-06-02 15:35 UTC, ebadiere approved these changes

2023-06-02 15:35 UTC, merged