Added configurable maxChunks parameter to the FileAppendTransaction
hashgraph/hedera-json-rpc-relay pull request #1300
Opened 2023-05-28 03:25 UTC by ebadiere

protobuf class.

**Related issue(s)**:

Fixes #980 

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-28 03:34 UTC, Nana-EC requested changes
Looking good.
Please update config name to `FILE_APPEND_MAX_CHUNKS` and see the configuration explanation suggestions provided

2023-05-28 03:34 UTC, Nana-EC commented on docs/configuration.md
> +| `MAX_CHUNKS`                      | "20"      | Default number of chunks for the protobuf FileAppendTransaction class to use to  when submitting a transaction to the mirror node.
```suggestion
| `FILE_APPEND_MAX_CHUNKS`                      | "20"      | Default maximum number of chunks for the `HAPI` `FileAppendTransaction` to use during contract creation submissions to consensus nodes as part of `eth_sendRawTransactionsaction`.                                                                                                                                                                                                                                                  |
```

2023-05-30 17:44 UTC, AlfredoG87 approved these changes
LGTM

2023-05-30 17:55 UTC, Nana-EC approved these changes

2023-05-30 19:13 UTC, merged