add manually triggered workflow for acceptance tests
hashgraph/hedera-json-rpc-relay pull request #1306
Opened 2023-05-29 13:35 UTC by Ivo-Yankov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-31 00:29 UTC, Nana-EC requested changes
Nice. Please simplify the contents of the env files to only set needed variables and overrides

2023-05-31 00:29 UTC, Nana-EC commented on packages/server/tests/previewnetAcceptance.env
> +# cypress metamask config
Most if not all the values below are not need in this and the  testnet file.
Can we simplify the files to only the ones that need to override the defaults.

2023-05-31 00:29 UTC, Nana-EC commented on .github/workflows/acceptance-public.yml
> +        description: 'The ED25519 DER encoded private key of the operator'
nit: key can be either type
```suggestion
        description: 'The ED25519 or ECDSA DER encoded private key of the operator'
```

2023-05-31 00:29 UTC, Nana-EC commented on packages/server/tests/previewnetAcceptance.env
> +RELAY_ENDPOINT='http://127.0.0.1:7546'
I don't think this is needed

2023-05-31 00:29 UTC, Nana-EC commented on packages/server/tests/previewnetAcceptance.env
> +# cypress metamask config
Should set `E2E_RELAY_HOST` as the desired HashIO link
This will ensure the tests don't spin up their own instance of the relay

2023-05-31 00:46 UTC, ebadiere reviewed
Thanks for doing this!

2023-06-07 02:52 UTC, Nana-EC submitted a review, later dismissed
LG unblocking but a few suggestion to be consistent in imports and usage of constants

2023-06-07 02:52 UTC, Nana-EC commented on packages/server/src/koaJsonRpc/index.ts
> +import constants from "@hashgraph/json-rpc-relay/dist/lib/constants";
Added but not used.

2023-06-07 02:52 UTC, Nana-EC commented on packages/ws-server/src/index.ts
> +import constants from "@hashgraph/json-rpc-relay/dist/lib/constants";
In some placed you use `@hashgraph/json-rpc-relay/src/lib/constants` in other places you use this.
Assuming the same we should be consistent

2023-06-07 02:53 UTC, Nana-EC commented
@Ivo-Yankov should be able to resolve items and check in what you've achieved so far. We can follow up with PRs since it won't run automatically

2023-06-07 23:12 UTC, Nana-EC approved these changes

2023-06-09 20:56 UTC, ebadiere approved these changes
LG

2023-06-09 23:44 UTC, Nana-EC requested changes
Waiting on clarity

2023-06-13 04:36 UTC, Nana-EC approved these changes

2023-06-13 04:37 UTC, merged