Set ETH_CALL_DEFAULT_TO_CONSENSUS_NODE to false
hashgraph/hedera-json-rpc-relay pull request #1320
Opened 2023-06-01 17:08 UTC by ebadiere

**Description**:
Set ETH_CALL_DEFAULT_TO_CONSENSUS_NODE to false.

Fixes #1311

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-01 18:31 UTC, Nana-EC requested changes
LG
Needs `eth_call` logic update

2023-06-01 20:15 UTC, ebadiere commented on charts/hedera-json-rpc-relay/values.yaml
> +  ETH_CALL_DEFAULT_TO_CONSENSUS_NODE: false
Updated.

2023-06-02 03:06 UTC, ebadiere commented on packages/relay/tests/lib/openrpc.spec.ts
> +    it('should execute "eth_call" against mirror node with an undefined ETH_CALL_DEFAULT_TO_CONSENSUS_NODE', async function () {
There was already a set of two tests with all the necessary set up called 'should execute "eth_call" against mirror node' and 'should execute "eth_call" against consensus node' that explicitly set the process.env.ETH_CALL_DEFAULT_TO_CONSENSUS_NODE in the openrpc.spec.ts.

2023-06-02 03:51 UTC, ebadiere commented on packages/relay/tests/lib/openrpc.spec.ts
> +    it('should execute "eth_call" against mirror node with an undefined ETH_CALL_DEFAULT_TO_CONSENSUS_NODE', async function () {
Moved all three tests to eth.spec.ts and added a sinon check.

2023-06-02 15:44 UTC, Nana-EC approved these changes

2023-06-02 21:11 UTC, merged