Helm chart deployment for eth_subcribe server
hashgraph/hedera-json-rpc-relay pull request #1321
Opened 2023-06-02 10:36 UTC by isavov

**Description**:
This PR adds a new helm chart in order to support deployment of the eth_subscribe/websocket interface for the relay.
* Add new helm chart

**Related issue(s)**:

Fixes #1296 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-03 04:06 UTC, Nana-EC requested changes
Nice addition.
Please simplify to cover the websocket server only for this chart

2023-06-03 04:06 UTC, Nana-EC commented on charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
> +data:
A lot of configs below are not utilized in the websocket server package.
Can you reduce this to only the ones utilized by the websocket server as the default configuration

2023-06-03 04:06 UTC, Nana-EC commented on charts/hedera-json-rpc-relay-websocket/templates/secret.yaml
> +apiVersion: v1
Q: Is this resource needed?
The websocket server streams from the mirror node only, so the below SDK config secrets should not be needed

2023-06-03 04:06 UTC, Nana-EC commented on charts/hedera-json-rpc-relay-websocket/values.yaml
> +config:
SImilar to configmap, this should only include configs for the webserver socket

2023-06-03 04:06 UTC, Nana-EC requested changes
Nice addition.
Please simplify to cover the websocket server only for this chart

2023-06-06 11:55 UTC, isavov commented
After digging deeper into the used and unused ENV variables I've limited them to the absolutely necessary.
In the process I've discovered one unnecessary variable in the `hedera-json-rpc-relay` helm chart and removed it in this PR, as the fix was minor and doesn't need a separate PR

@Nana-EC What should the default value for `WS_MULTIPLE_ADDRESSES_ENABLED` be? I've set it to `false` for now, but I'm not sure if that would be best.

2023-06-06 13:05 UTC, Nana-EC commented
> After digging deeper into the used and unused ENV variables I've limited them to the absolutely necessary.
> 
> In the process I've discovered one unnecessary variable in the `hedera-json-rpc-relay` helm chart and removed it in this PR, as the fix was minor and doesn't need a separate PR
> 
> 
> 
> @Nana-EC What should the default value for `WS_MULTIPLE_ADDRESSES_ENABLED` be? I've set it to `false` for now, but I'm not sure if that would be best.

False is the right value to start with. We'll build confidence and when ready switch to true.

2023-06-06 14:54 UTC, Nana-EC submitted a review, later dismissed
LGTM

2023-06-06 15:38 UTC, AlfredoG87 requested changes
LGTM,
just 1 request.

Could you include the new helm chart on the bump-version script, similar to how it is the prior one?

https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/scripts/.bump-version.js#L67-L85

2023-06-06 15:38 UTC, AlfredoG87 requested changes
LGTM,
just 1 request.

Could you include the new helm chart on the bump-version script, similar to how it is the prior one?

https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/scripts/.bump-version.js#L67-L85

2023-06-06 15:51 UTC, ebadiere reviewed
What does this mean?  Will I not be able to run tests against the ws server in the local node?

2023-06-06 15:56 UTC, Nana-EC commented on charts/hedera-json-rpc-relay-websocket/ci/default-values.yaml
> +# Default values for json-rpc-relay in CI. Configured to testnet
In a follow up PR we should add a test pod under this charts template to verify it on chart install in CI

2023-06-06 15:57 UTC, Nana-EC commented
> What does this mean? Will I not be able to run tests against the ws server in the local node?

Shouldn't affect local runs, just the chart being deployed in production flow.

2023-06-06 16:00 UTC, AlfredoG87 approved these changes
LGTM

2023-06-06 16:02 UTC, ebadiere submitted a review, later dismissed
LG

2023-06-06 16:10 UTC, AlfredoG87 approved these changes
LGTM

2023-06-07 05:24 UTC, isavov commented
> LGTM, just 1 request.
> 
> Could you include the new helm chart on the bump-version script, similar to how it is the prior one?
> 
> https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/scripts/.bump-version.js#L67-L85

Thanks for including it in the bump script, I completely missed that 🙌

2023-06-07 05:30 UTC, merged

2023-06-08 02:16 UTC, Nana-EC commented on charts/hedera-json-rpc-relay-websocket/ci/default-values.yaml
> +# Default values for json-rpc-relay in CI. Configured to testnet
@isavov making sure you saw this one to add it to any follow up PRs