Update gas calculation in eth method
hashgraph/hedera-json-rpc-relay pull request #136
Opened 2022-06-02 15:04 UTC by ar-conmit

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:
- add `getNetworkFees` to retrieve fees from mirror-node
- update `getFeeWeibars` to use `getNetworkFees` and convert them in weibars
- update `eth_gasPrice` to return the actual gas price in weibars
- add cache functionallity to `eth_gasPrice` TBD

**Related issue(s)**:

Fixes #118 

**Notes for reviewer**:
Under investigation: There is a strange behaviour between `js-cache` module and `lerna` test jobs. When cache `ttl` is set and the test cases are ran via `lerna`, the test cases are waiting for the same amount of time as specified in `ttl` before continuing with the other test cases. Example if `ttl` of 10sec is specified, the `lerna` tests will wait for 10sec before continuing 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-03 07:35 UTC, Daniel-K-Ivanov requested changes

2022-06-03 07:35 UTC, Daniel-K-Ivanov commented on packages/relay/src/lib/eth.ts
> +          .multiply(10_000_000_000);
I assume that we have this constant used somewhere else. We can declare it as variable

2022-06-03 14:34 UTC, Nana-EC commented on packages/relay/src/lib/constants.ts
> +};
nit: new line

2022-06-03 14:35 UTC, Nana-EC commented on packages/relay/src/lib/constants.ts
> +    EXCHANGE_RATE_FILE_ID: "0.0.112",
nit:
```suggestion
    EXCHANGE_RATE_FILE_ID: '0.0.112',
```

2022-06-03 14:37 UTC, Nana-EC commented on packages/relay/src/lib/constants.ts
> +    EXCHANGE_RATE_FILE_ID: "0.0.112",
Q: I don't see this used. Did you mean to consume it in `MirrorNodeClient`?
Can remove if not used

2022-06-03 14:38 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
> +      const txFee = networkFees.fees.find(({transaction_type}) => transaction_type === "EthereumTransaction");
Make `EthereumTransaction` a static field.
Or add to constants if it is used elsewhere

2022-06-03 19:08 UTC, mmrt approved these changes

2022-06-03 22:48 UTC, Nana-EC commented
So even with the new API mirror node returns 404 in a new env since there are no exchange rate records submitted.
We need to add a backup flow whereby if MirrorNode returns null we consult the network.

2022-06-04 01:11 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
> +      const feeSchedules = await this.sdkClient.getFeeSchedule();
Coverage for this will have to come with future integration tests that use `sinon` to mock `SDKClient class`

2022-06-04 01:12 UTC, Nana-EC approved these changes
LG

2022-06-06 09:47 UTC, Daniel-K-Ivanov approved these changes

2022-06-06 10:14 UTC, merged