Ignore test files in sonar cloud checks
hashgraph/hedera-json-rpc-relay pull request #1376
Opened 2023-06-20 08:46 UTC by Ivo-Yankov

**Description**:

Something seems to have changed in the default SonarCloud configuration and every PR has a lot of code smells and code duplication warnings that cause the SonarCloud check to fail. All of the warnings are related to very old code and I think that the test files used to be ignored by default. This PR brings back the previous default behaviour.

- Adds a config file for SonarCloud
- Ignores all test files from SonarCloud checks

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-06-20 16:12 UTC, AlfredoG87 approved these changes
LGTM

2023-06-21 05:13 UTC, Nana-EC requested changes
Q: Why ignore them vs fix them? 
Granted it's annoying at first but maybe we should just address the sonar complaints and maintain the improvements as they increase readability and have caught some code smells that should be in the code

2023-06-21 07:27 UTC, Ivo-Yankov commented
> Q: Why ignore them vs fix them? Granted it's annoying at first but maybe we should just address the sonar complaints and maintain the improvements as they increase readability and have caught some code smells that should be in the code

I agree that we should fix them, but maybe it's better to do that at a planned time and in a dedicated PR - this way the current PRs won't be blocked and we won't encounter a lot of conflicts from everyone trying to fix the same code smells on their own. 

Also a lot of the test suites require major refactoring at this point - for example `eth.spec.ts` has grown to almost 5000 lines of code.

2023-06-23 04:56 UTC, Nana-EC commented
> > Q: Why ignore them vs fix them? Granted it's annoying at first but maybe we should just address the sonar complaints and maintain the improvements as they increase readability and have caught some code smells that should be in the code
> 
> I agree that we should fix them, but maybe it's better to do that at a planned time and in a dedicated PR - this way the current PRs won't be blocked and we won't encounter a lot of conflicts from everyone trying to fix the same code smells on their own.
> 
> Also a lot of the test suites require major refactoring at this point - for example `eth.spec.ts` has grown to almost 5000 lines of code.

I don't see any PRs being blocked by sonar right now. My concern is removing the checks will push this into tech debt territory that never gets addressed.
I think a few edits here and there as we see the sonar warnings will push up to get it done over time

2023-06-23 14:55 UTC, Ivo-Yankov commented
> > > Q: Why ignore them vs fix them? Granted it's annoying at first but maybe we should just address the sonar complaints and maintain the improvements as they increase readability and have caught some code smells that should be in the code
> > 
> > 
> > I agree that we should fix them, but maybe it's better to do that at a planned time and in a dedicated PR - this way the current PRs won't be blocked and we won't encounter a lot of conflicts from everyone trying to fix the same code smells on their own.
> > Also a lot of the test suites require major refactoring at this point - for example `eth.spec.ts` has grown to almost 5000 lines of code.
> 
> I don't see any PRs being blocked by sonar right now. My concern is removing the checks will push this into tech debt territory that never gets addressed. I think a few edits here and there as we see the sonar warnings will push up to get it done over time

Fair point, I'm closing the PR

2023-06-23 14:55 UTC, closed without merging