add postman tests
hashgraph/hedera-json-rpc-relay pull request #143
Opened 2022-06-02 19:36 UTC by mmrt

Closes #77 

Adds postman tests mirroring existing tests.

Signed-off-by: Mitchell Martin <mitch@swirldslabs.com>

2022-06-02 20:01 UTC, Nana-EC commented on packages/server/tests/postman.json
> +			"name": "eth_accounts",
e.g. https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-web3/postman.json#L54

2022-06-02 20:16 UTC, Nana-EC commented on packages/server/tests/postman.json
> +			"name": "eth_accounts",
Actually you got some unsupported. So just an invalid method test case

2022-06-03 00:17 UTC, mmrt commented on packages/server/tests/postman.json
> +}
done

2022-06-03 00:17 UTC, mmrt commented on packages/server/tests/postman.json
> +					"raw": "http://34.122.35.80:7546",
done

2022-06-03 00:40 UTC, Nana-EC requested changes
IP updated and missing no matching method test caes

2022-06-03 00:40 UTC, Nana-EC commented on README.md
> +newman run packages/server/tests/postman.json --env-var baseUrl=http://34.122.35.80:7546
```suggestion
newman run packages/server/tests/postman.json --env-var baseUrl=http://localhost:7546
```
or
```suggestion
newman run packages/server/tests/postman.json --env-var baseUrl=http://127.0.0.1:7546
```

2022-06-03 00:40 UTC, Nana-EC commented on packages/server/tests/postman.json
> +	  "value": "34.122.35.80:7546",
```suggestion
	  "value": "locahost:7546",
```
or
```suggestion
	  "value": "127.0.0.1:7546",
```
Either but should be consistent with what you put in README

2022-06-03 00:40 UTC, Nana-EC commented on packages/server/tests/postman.json
> +		  "raw": "{\n    \"id\": \"test_id\",\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"web3_clientVersion\",\n    \"params\": []\n}",
Still missing a case where the method called is not applicable
In the example postman.json I linked we did this by calling a non existent method e.g.
```
		  "raw": "{\n    \"id\": \"test_id\",\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"unknown\",\n    \"params\": []\n}",
```

2022-06-03 15:08 UTC, mmrt commented on packages/server/tests/postman.json
> +			"name": "eth_accounts",
missed this, added invalid as well

2022-06-03 15:13 UTC, Nana-EC approved these changes
LG. Just DCO issue

2022-06-03 15:29 UTC, Nana-EC approved these changes

2022-06-03 15:42 UTC, merged