Update eth_getTransactionCount to return contract nonce
hashgraph/hedera-json-rpc-relay pull request #1535
Opened 2023-07-18 14:41 UTC by Ivo-Yankov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-07-19 15:00 UTC, AlfredoG87 submitted a review, later dismissed
LGTM 👍

2023-07-19 18:45 UTC, Nana-EC requested changes
Realized we need to handle and test for null response on historical contracts

2023-07-19 18:45 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
>        return EthImpl.numberTo0x(accountData.ethereum_nonce);
Actually we now have to handle the null case.
Historical contracts that didn't track the nonce will return a null on this.
In this case you can be assured it's a contract and you should send back `EthImpl.oneHex`
e.g. https://previewnet.mirrornode.hedera.com/api/v1/accounts/0.0.1036

2023-07-19 18:45 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
>        return EthImpl.numberTo0x(accountData.ethereum_nonce);
```suggestion
      // with HIP 729 ethereum_nonce should always be 0+ and null. Historical contracts may have a null value as the nonce was not tracked, return default EVM compliant 0x1 in this case
      return accountData.ethereum_nonce ? EthImpl.numberTo0x(accountData.ethereum_nonce) : EthImpl.oneHex;
```

2023-07-20 14:04 UTC, Nana-EC submitted a review, later dismissed

2023-07-20 18:42 UTC, Nana-EC reviewed
Looking good. Test fixes but also the mirrorNoceClient.handleError change I think should be revert and the management logic pushed to the eth classes

2023-07-20 18:42 UTC, Nana-EC commented on packages/relay/src/lib/clients/mirrorNodeClient.ts
> +            // Handles a FAIL_INVALID error thrown in the case of a non-existing contract in /contracts/call
This should be managed at the `eth_x` method level

2023-07-20 18:42 UTC, Nana-EC commented on packages/relay/src/lib/clients/mirrorNodeClient.ts
> +            // Handles a FAIL_INVALID error thrown in the case of a non-existing contract in /contracts/call
`handleError` should really only manage fundamental retries and then throw a valid `MirrorNOdeClientError`.
Eth methods should decide for themselves how to handle the errors.

2023-07-25 00:01 UTC, Nana-EC submitted a review, later dismissed

2023-07-31 19:44 UTC, ebadiere approved these changes
LG.

2023-07-31 19:54 UTC, Nana-EC approved these changes

2023-07-31 20:55 UTC, merged