Support synthetic logs in eth_subscribe
hashgraph/hedera-json-rpc-relay pull request #1675
Opened 2023-08-23 12:52 UTC by Ivo-Yankov

**Description**:
Fixes the address validation logic before creating a subscription through `eth_subscribe`. It now checks if the address is of an existing contract or token. This makes it possible to subscribe to `transfer` and `approve` events generated by HTS tokens.

**Related issue(s)**:

Fixes #1602

2023-08-23 15:57 UTC, Nana-EC requested changes
Looking good.
Seems like the PR is trying to support subscribing to logs where the address is for an HTS token. Please update the PR with an appropriate description and see my other suggestions

2023-08-23 15:57 UTC, Nana-EC commented on packages/ws-server/src/webSocketServer.ts
>  async function validateIsContractAddress(address, requestId) {
nit: rename the method since it's doing more than it states

2023-08-23 15:57 UTC, Nana-EC commented on packages/ws-server/src/webSocketServer.ts
> +    const isContractOrToken = await mirrorNodeClient.resolveEntityType(address, [constants.TYPE_CONTRACT, constants.TYPE_TOKEN], 'eth_subscribe', requestId)
Use a constant for `eth_subscribe`.

2023-08-23 22:58 UTC, AlfredoG87 approved these changes
LGTM 👍

2023-08-24 18:29 UTC, Nana-EC approved these changes
LG

2023-08-25 06:52 UTC, merged