Apply formatting
hashgraph/hedera-json-rpc-relay pull request #1704
Opened 2023-09-01 16:08 UTC by georgi-l95

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-03 19:54 UTC, AlfredoG87 submitted a review, later dismissed
I am afraid this will break and ask for rebase of every single outstanding PRs but nevertheless worth to have conventions implemented on the project 👍

2023-09-05 10:42 UTC, georgi-l95 commented
@AlfredoG87 i've rebased and lost approval

2023-09-05 20:09 UTC, Nana-EC commented on .prettierrc
> +    "singleQuote": false,
I prefer single actually 😆

2023-09-05 20:10 UTC, Nana-EC requested changes
Thanks.
Blocking whiles I confirm some items

2023-09-05 20:11 UTC, ebadiere approved these changes
Mainly single quotes to double quotes, added semi-colons and some method call formatting.  LGTM.

2023-09-06 10:24 UTC, georgi-l95 commented on .prettierrc
> +    "singleQuote": false,
Okay, done, switched to single :D

2023-09-06 12:31 UTC, merged