Set the mirror-image-tage t- 0.87.0 from main
hashgraph/hedera-json-rpc-relay pull request #1721
Opened 2023-09-06 17:16 UTC by ebadiere

Set the mirror node tag version to 0.87.0

**Related issue(s)**:

Fixes #1706

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-06 17:20 UTC, AlfredoG87 approved these changes
LGTM

2023-09-07 16:19 UTC, Nana-EC requested changes
Update this to the latest beta - https://github.com/hashgraph/hedera-mirror-node/releases

2023-09-14 22:50 UTC, Nana-EC requested changes

2023-09-14 22:50 UTC, Nana-EC commented on packages/server/tests/acceptance/index.spec.ts
> +    process.env['MIRROR_IMAGE_TAG'] = '0.87.0';
```suggestion
    process.env['MIRROR_IMAGE_TAG'] = '0.88.0';
```

2023-09-16 02:32 UTC, Nana-EC approved these changes

2023-09-16 02:33 UTC, merged