Add basic positive tests for contract creation with transactions of t…
hashgraph/hedera-json-rpc-relay pull request #1758
Opened 2023-09-21 08:06 UTC by anastasiya-kovaliova

**Description**:
Adding 1 basic test per transaction type via 2930 and 1559 for a contract creation with a real contract.

**Related issue(s)**:

Task: #1730 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-21 14:04 UTC, ebadiere approved these changes
LG.

2023-09-23 23:36 UTC, ebadiere requested changes
There is a test consistently failing

2023-09-29 16:23 UTC, Nana-EC approved these changes

2023-10-02 16:01 UTC, ebadiere approved these changes
LG.

2023-10-02 16:01 UTC, merged