Add acceptance tests for debug_traceTransaction endpoint
hashgraph/hedera-json-rpc-relay pull request #1814
Opened 2023-10-11 12:27 UTC by anastasiya-kovaliova

**Description**:
This PR adds acceptance tests to cover the behaviour of the debug_traceTransaction in both positive and negative scenarious:

- Adds positive and negative acceptance tests
- Adds tests brief description in the design document

**Related issue(s):**

**Fixes** 
#1792 

Notes for reviewer:
The ticket for implementing the debug_traceTransaction is: #1477 

Checklist

- [ ]  Documented (Code comments, README, etc.)
- [ ]  Tested (unit, integration, etc.)

2023-10-11 16:42 UTC, Nana-EC requested changes
Looking good.
minor suggestions.
Also please add `@release` in one or two of the happy path tests so they get picked up with release testing.

2023-10-11 16:42 UTC, Nana-EC commented on packages/server/tests/helpers/assertions.ts
> +    //Validate result schema
nits:
```suggestion
    // Validate result schema
```

2023-10-11 16:42 UTC, Nana-EC commented on packages/server/tests/acceptance/rpc_batch3.spec.ts
> +      transactionType2 = {
use `...defaultTransactionFields` as you did in the above

2023-10-11 16:42 UTC, Nana-EC commented on packages/server/tests/acceptance/rpc_batch3.spec.ts
> +        chainId: 0x12a,
Q: should already be captured by `transactionTypeLegacy` right?

2023-10-12 18:52 UTC, Nana-EC approved these changes

2023-10-13 11:07 UTC, konstantinabl commented on packages/server/tests/acceptance/rpc_batch3.spec.ts
> +        type: 1,
@anastasiya-kovaliova TransactionType2930 should also have field accessList: []

2023-10-13 11:15 UTC, konstantinabl requested changes

2023-10-13 11:15 UTC, konstantinabl commented on packages/server/tests/acceptance/rpc_batch3.spec.ts
> +        chainId: Number(CHAIN_ID),
@anastasiya-kovaliova Is there a reason we have chainId overwritten here?

2023-10-13 11:15 UTC, konstantinabl commented on packages/server/tests/acceptance/rpc_batch3.spec.ts
> +          let signedTransaction = await accounts[0].wallet.signTransaction(transaction);
@anastasiya-kovaliova You can use const for the variables that do not get reassigned, like thos two : )) There were other places as well

2023-10-13 11:15 UTC, konstantinabl commented on packages/server/tests/helpers/assertions.ts
> +    let hasValidHash = (currentValue) => RelayAssertions.validateHash(currentValue);
@anastasiya-kovaliova Here you can use const as well

2023-10-13 11:15 UTC, konstantinabl commented on packages/server/tests/helpers/assertions.ts
> +  static validateResultDebugValues = (result, excludedValues, nestedExcludedValues, expectedResult) => {
@anastasiya-kovaliova Please add types as well - for the parameters, the return value and the variables in the function. I know we do not have them in a lot of places, but we should start adding them

2023-10-17 00:28 UTC, Nana-EC approved these changes

2023-10-17 01:42 UTC, AlfredoG87 approved these changes
LGTM

2023-10-17 10:16 UTC, konstantinabl approved these changes

2023-10-17 10:16 UTC, konstantinabl commented
LG

2023-10-17 12:24 UTC, merged