use empty trie if no transactions in list
hashgraph/hedera-json-rpc-relay pull request #185
Opened 2022-06-09 19:51 UTC by mmrt

Signed-off-by: Mitchell Martin <mitch@swirldslabs.com>

**Description**:
Return the [proper transactionRoot](https://eth.wiki/json-rpc/API#:~:text=%22transactionsRoot%22%3A%20%220x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421%22%2C) if no transactions exist (instead of blockhash). 

**Related issue(s)**:

Fixes #179

2022-06-10 20:42 UTC, Nana-EC requested changes
Looks good but you're missing tests

2022-06-10 20:42 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
> +      transactionsRoot: transactionArray.length == 0 ? EthImpl.ethEmptyTrie : blockHash,
This needs coverage in `eth.spec.ts`

2022-06-13 18:51 UTC, mmrt commented on packages/relay/src/lib/eth.ts
> +      transactionsRoot: transactionArray.length == 0 ? EthImpl.ethEmptyTrie : blockHash,
coverage now exists

2022-06-13 18:53 UTC, Nana-EC requested changes
Looks good, but I think there's a simpler way on the mocking side.
Should be quick fix and we can get this in

2022-06-13 18:53 UTC, Nana-EC commented on packages/relay/tests/lib/eth.spec.ts
> +    mock.onGet(`contracts/results?timestamp=gte:${defaultBlock.timestamp.from}&timestamp=lte:${defaultBlock.timestamp.to}`).reply(200, defaultContractResults);
A better way would be modify defaultContractResults to return an empty array here.
In this way the follow up `contracts/${contractAddress1}/results` are not made and the mocking is not needed. 
```suggestion
    mock.onGet(`contracts/results?timestamp=gte:${defaultBlock.timestamp.from}&timestamp=lte:${defaultBlock.timestamp.to}`).reply(200, { 'results': []});
```

2022-06-13 18:53 UTC, Nana-EC commented on packages/relay/tests/lib/eth.spec.ts
> +  const defaultEmptyContractResults = {
not needed with my suggestion below

2022-06-13 19:32 UTC, mmrt commented on packages/relay/tests/lib/eth.spec.ts
> +  const defaultEmptyContractResults = {
removed

2022-06-13 19:33 UTC, Nana-EC approved these changes
LGTM

2022-06-13 19:34 UTC, merged