++ SimpleVault to demo system contract mocks
hashgraph/hedera-json-rpc-relay pull request #1884
Opened 2023-11-08 08:46 UTC by mshakeg

**Description**:

Demos how to utilize the Hedera system contract mocks in a hardhat project(against a local hardhat node) by duplicating an instance of a given mock contract to the Hedera defined system contract address using the `hardhat_setCode` method.

**Related issue(s)**:

Fixes the hardhat component of https://github.com/hashgraph/hedera-json-rpc-relay/issues/1172

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-12-06 02:39 UTC, Nana-EC commented
@mshakeg please rebase, we'll review this sprint

2023-12-26 20:01 UTC, Nana-EC commented
@AlfredoG87 & @ebadiere please review

2023-12-27 19:14 UTC, AlfredoG87 requested changes
LG, just 1 nit and a question

2023-12-27 19:14 UTC, AlfredoG87 commented on tools/hardhat-example/.env.example
> +MNEMONIC="here is where your twelve words mnemonic should be put my friend"
please add a blank line at the end of the file

2023-12-27 19:14 UTC, AlfredoG87 commented on tools/hardhat-example/test/simple-vault.js
> +    const expectedTokenAddress = createTokenExpectedResult.tokenAddress; // TODO: investigate why computing the expected address using the factory address and nonce doesn't work
Is this TODO still pending?

2023-12-27 19:14 UTC, AlfredoG87 commented
Also, in order for the tests to pass, please rebase to latest version of main.

2023-12-28 10:35 UTC, mshakeg commented on tools/hardhat-example/test/simple-vault.js
> +    const expectedTokenAddress = createTokenExpectedResult.tokenAddress; // TODO: investigate why computing the expected address using the factory address and nonce doesn't work
fixed

2023-12-28 10:46 UTC, mshakeg commented
Hey @Nana-EC do you think there'd be significant value in say applying these changes to an existing hardhat project such as [Uniswap/v3-core](https://github.com/Uniswap/v3-core) to demonstrate how projects can easily adapt their codebases for Hedera? If so, I might consider doing it.

2023-12-28 20:10 UTC, AlfredoG87 reviewed
Looks good, please rebase and resolve conflicts.

2023-12-29 21:36 UTC, AlfredoG87 commented
it seems like the `package.json` and `package-lock.json` are out of sync after the rebase, could you just run 
`npm install` and push the changes to the `package-lock.json` file? This is making the tests fail

2023-12-29 21:37 UTC, AlfredoG87 requested changes
please update `package-lock.json` by running `npm install`

2023-12-30 00:02 UTC, Nana-EC commented
> Hey @Nana-EC do you think there'd be significant value in say applying these changes to an existing hardhat project such as [Uniswap/v3-core](https://github.com/Uniswap/v3-core) to demonstrate how projects can easily adapt their codebases for Hedera? If so, I might consider doing it.

@mshakeg great idea, I think adding a `contracts/uniswap/v3-core` example under https://github.com/hashgraph/hedera-smart-contracts/tree/main/contracts which matching test support would be the right approach.
Did you want to create an issue or PR for this in that repo?

2023-12-30 08:42 UTC, mshakeg commented
@Nana-EC no I did not, I think it would be better to fork the uniswap/v3-core repo, apply the changes and perhaps leave a PR open from the fork to `uniswap/v3-core@main` for developers to easily see the changes necessary for integrating with Hedera.

2023-12-30 08:46 UTC, mshakeg commented
> please update `package-lock.json` by running `npm install`

2023-12-30 08:49 UTC, mshakeg commented
@AlfredoG87 hopefully that's the last time I have to do that :)

2024-01-03 15:54 UTC, AlfredoG87 commented
@mshakeg Thank you!
Most of the tests are passing now, there is only an issue with the `dapp-tests`

```Error HH18: You installed Hardhat with a corrupted lockfile due to the NPM bug #4828.

Please delete your node_modules, package-lock.json, reinstall your project, and try again.

HardhatError: HH18: You installed Hardhat with a corrupted lockfile due to the NPM bug #4828.
```
see [here](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/7363125172/job/20107602135?pr=1884)

Please follow the instructions and push the changes to the `package-lock.json` file after is fixed.

2024-01-05 12:37 UTC, mshakeg commented
@AlfredoG87 I've merged main into this branch, so those files(`package.json` and `package-lock.json`) are now unchanged.

2024-01-08 23:51 UTC, mshakeg commented
@AlfredoG87 seems like it's in a much better state. It failed initially due to me having installed with node 20, but the workflow is currently set to use node 18, so I re-installed using that version, and it then failed due to a compilation error(seems like there's been changes to the mocks I initially developed?) so I locked it to use my version of the mocks.

2024-01-09 00:26 UTC, AlfredoG87 submitted a review, later dismissed

2024-01-10 15:54 UTC, AlfredoG87 commented
@mshakeg 

I am sorry, there are some conflicts on the `package.json` and `package-lock.json` again 😓 
I should have merged it when I had the chance, just wanted to give folks some time to review in case there were other comments.

once this rebase and conflicts are resolved I will re-approve and merge.

2024-01-10 16:58 UTC, AlfredoG87 commented
@mshakeg 
we are seeing the error 
```
Please delete your node_modules, package-lock.json, reinstall your project, and try again.
```
https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/7477530404/job/20350428264?pr=1884

is it the node version again?

2024-01-10 17:16 UTC, mshakeg commented
@AlfredoG87 seems so. Hopefully that fixes it.

2024-01-10 19:04 UTC, AlfredoG87 approved these changes
LGTM

2024-01-10 19:04 UTC, merged