feat:  improved metrics and added rate limit for the batch request feature in ws server (#2474)
hashgraph/hedera-json-rpc-relay pull request #2487
Opened 2024-05-13 19:08 UTC by quiet-node

**Description**:
- added `shouldRateLimitOnMethod()` function to ConnectionLimiter class which utilizes the `shouldRateLimit()` method from `RateLimit` class to apply rate limit logic on both batch requests and single requests in the WS server
- added methodsCounter metric for `batch_requests` methods

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-13 23:48 UTC, Nana-EC requested changes
LG.
Missing acceptance tests

2024-05-13 23:48 UTC, Nana-EC commented on packages/ws-server/src/webSocketServer.ts
> +      if (limiter.shouldRateLimitOnMethod(ctx.ip, WS_CONSTANTS.BATCH_REQUEST_METHOD_NAME, ctx.websocket.requestId)) {
Tests?
I think the relay has a test setup that you can mimic e.g. set the rate limit small and send requests to exceed it and verify

2024-05-14 02:00 UTC, AlfredoG87 requested changes
as @Nana-EC pointed is missing UT for rate limits.

also, atm we don't do automated tests for `metrics` but we usually add a screenshot of the `/metrics` endpoint where you can see the metrics added with some values on **Notes for reviewer:** section of the PR description.

2024-05-14 19:39 UTC, quiet-node commented
> as @Nana-EC pointed is missing UT for rate limits.
> 
> also, atm we don't do automated tests for `metrics` but we usually add a screenshot of the `/metrics` endpoint where you can see the metrics added with some values on **Notes for reviewer:** section of the PR description.

added prrof for metrics

2024-05-16 04:12 UTC, AlfredoG87 approved these changes
LGTM

2024-05-16 14:54 UTC, Nana-EC approved these changes

2024-05-16 15:03 UTC, quiet-node commented on .github/workflows/acceptance.yml
> +      test_ws_server: true
> Q: what's this config and why is it just for ws.

This config sets the `process.env.TEST_WS_SERVER` variable in the [CI job](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/.github/workflows/acceptance-workflow.yml#L87). The test program uses this `TEST_WS_SERVER` environment variable to determine whether to run the WS server, as shown [here](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/ws-server/tests/acceptance/index.spec.ts#L175).

> Shouldn't we test all the time or if there is a config shouldn't there be on for the HTTP and the WS server each?
We didn't have tests for rate limiting on the WS server until this PR. Previously, we only had them for the HTTP server. That's why this workflow has been running exclusively against the HTTP server.

2024-05-16 15:45 UTC, merged