fix: ws errors should conform to jsonrpc spec
hashgraph/hedera-json-rpc-relay pull request #2505
Opened 2024-05-17 18:58 UTC by ted-yeh-vc

**Description**:

This PR fixes the error returned from websockets being closed to be conformant to json rpc spec re: errors.
https://www.jsonrpc.org/specification#error_object
**Related issue(s)**:

Fixes #2362

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-17 19:14 UTC, ted-yeh-vc commented
I could be in the wrong, but it seems unnecessary to push an error to the client before closing the connection. The connection closing has its own code and message. Was there a particular reason the separate message is being sent?

2024-05-20 13:34 UTC, quiet-node commented
> I could be in the wrong, but it seems unnecessary to push an error to the client before closing the connection. The connection closing has its own code and message. Was there a particular reason the separate message is being sent?

Hi @ted-yeh-vc thanks for poiniting it out! You're right the closing connection has its own code and message, when I pushed in the update I thought it could make it a little more informative for some users by informing them the error before closing the connection. Just a little slight touch on the UX. I will discuss with the team and get back to you later!

2024-05-21 14:25 UTC, quiet-node requested changes
So, I discussed with my team and we decided to keep the current layout with the extra piece of message sent back to the client. Also, we aggreed that your approach to make the error conform to jsonrpc spec is necessary, and we want the errors to have a consistent structure. Please find the change suggestion below for the new structure. Thanks a lot for the time and effort!

2024-05-21 14:25 UTC, quiet-node commented on packages/ws-server/src/metrics/connectionLimiter.ts
> +          },
```suggestion
          error: {
            code: CONNECTION_LIMIT_EXCEEDED.code,
            message: CONNECTION_LIMIT_EXCEEDED.message,
            data: {
              message: CONNECTION_LIMIT_EXCEEDED.message,
              max_connection: MAX_CONNECTION_LIMIT,
            },
          },
```

2024-05-21 14:25 UTC, quiet-node commented on packages/ws-server/src/metrics/connectionLimiter.ts
> +          },
```suggestion
          error: {
            code: CONNECTION_IP_LIMIT_EXCEEDED.code,
            message: CONNECTION_IP_LIMIT_EXCEEDED.message,
            data: {
              message: CONNECTION_IP_LIMIT_EXCEEDED.message,
              max_connection: MAX_CONNECTION_LIMIT_PER_IP,
            },
          },
```

2024-05-21 14:25 UTC, quiet-node commented on packages/ws-server/src/metrics/connectionLimiter.ts
> +              },
```suggestion
              error: {
                code: TTL_EXPIRED.code,
                message: TTL_EXPIRED.message,
                data: {
                  message: TTL_EXPIRED.message,
                  max_inactivity_TTL: maxInactivityTTL,
                },
              },
```

2024-05-21 15:20 UTC, ted-yeh-vc commented
Fantastic. Thanks for the quick review. Always happy to help!

2024-05-22 02:18 UTC, quiet-node approved these changes
LGTM

2024-05-22 02:19 UTC, quiet-node commented
@ted-yeh-vc looks like the first commit didn't get verified. Please fix it for the PR to be mergable.

2024-05-23 17:04 UTC, Nana-EC approved these changes
LGTM

2024-05-23 23:30 UTC, merged