feat: Checking in the grafana dashboard into the reposity.
hashgraph/hedera-json-rpc-relay pull request #2658
Opened 2024-07-02 19:14 UTC by ebadiere

Versioning the Grafana dashboard into the repository, and added a panel.

**Related issue(s)**: #2654 

Fixes #

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-04 04:01 UTC, Nana-EC requested changes
Dashboard file already exists in `dashboards/hedera-json-rpc-relay-http-server.json`, you should be updating that instead

2024-07-15 15:51 UTC, quiet-node submitted a review, later dismissed

2024-07-15 19:04 UTC, Nana-EC approved these changes

2024-07-16 17:32 UTC, quiet-node approved these changes

2024-07-16 17:34 UTC, merged