fix: fixtures usage example
hashgraph/hedera-json-rpc-relay pull request #2704
Opened 2024-07-16 11:09 UTC by arianejasuwienas

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-05 17:29 UTC, acuarica commented
Hi @arianejasuwienas, thanks for sending this. Could you please fill in the PR description? So we are aware what motivated this change.

2024-08-05 17:32 UTC, acuarica requested changes

2024-08-05 17:32 UTC, acuarica commented on tools/waffle-example/test/samplecontract.test.mjs
> +
This should be move inside a `before` or `beforeEach` block.

2024-08-26 14:37 UTC, acuarica commented
Hey @arianejasuwienas, there are some outstanding comments. Would you be able to address them so we can merge this?

2024-08-26 16:55 UTC, acuarica approved these changes
lg

2024-08-28 06:35 UTC, natanasow approved these changes
LGTM

2024-08-28 11:23 UTC, merged