fix: debug_traceTransaction params are inconsistent with other providers
hashgraph/hedera-json-rpc-relay pull request #2778
Opened 2024-08-01 11:55 UTC by victor-yanev

**Description**:

Description

The current parameters that we accept for the debug_traceTransaction endpoint are inconsistent with what other providers expect. Also debugging transactions in Remix is not working currently because of that.

References:

https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracetransaction
https://docs.chainstack.com/reference/ethereum-tracetransaction
https://docs.infura.io/api/networks/linea/json-rpc-methods/debug/debug_tracetransaction
https://docs.alchemy.com/reference/debug-tracetransaction
https://www.quicknode.com/docs/ethereum/debug_traceTransaction

**Related issue(s)**:

Fixes #2777 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-12 16:21 UTC, quiet-node requested changes
Great work! Just a couple of suggestions

2024-08-12 16:21 UTC, quiet-node commented on packages/relay/src/lib/services/debugService/index.ts
>  const SUCCESS = 'SUCCESS';
This can go to constants.ts

2024-08-13 13:54 UTC, victor-yanev commented on packages/relay/src/lib/services/debugService/IDebugService.ts
>   */
The `IDebugService` interface is meant to define the contract for the debug service class, outlining the methods that need to be implemented by the service class.

On the other hand, `ITracerConfig` and `ITracerConfigWrapper` define the configuration objects for tracing. While these configurations are used by the debug service, they are conceptually distinct and they shouldn't be placed in the same file.

Btw, service interfaces are placed in the same directory as their service implementations throughout the project. So, it makes sense to stick with this pattern here too.

2024-08-19 20:57 UTC, acuarica submitted a review, later dismissed
lg, left some questions

2024-08-20 11:32 UTC, victor-yanev commented on packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
> +import { createStubInstance, SinonStub, SinonStubbedInstance, stub } from 'sinon';
Yes, sorry about that! 

I forgot to turn off the "Optimize imports" option in my IDE when I was doing a merge commit from the main branch and I clicked on cancel, but it already had processed some files. 😅

2024-08-26 14:27 UTC, jeromy-cannon approved these changes

2024-08-26 14:54 UTC, acuarica submitted a review, later dismissed
lg

2024-08-27 10:34 UTC, konstantinabl approved these changes

2024-08-27 14:25 UTC, quiet-node approved these changes

2024-08-27 14:59 UTC, merged