feat: calculate actual `receiptsRoot` when possible
hashgraph/hedera-json-rpc-relay pull request #2798
Opened 2024-08-07 11:58 UTC by natanasow

**Description**:

Currently, when we return block information, we don't include actual receiptsRoot, this is because Hedera is not using Merkle Patricia trie. However, this can be easily calculated during the processing of the request. Returning real `receiptsRoot` can help tools and developers.

**Solution**:

Taking a look at how calculating receiptsRoot is done in the javascript execution client for Ethereum can help us do it here as well. More information about the implementation can be found [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/buildBlock.ts#L155).

**Related issue(s)**:

Fixes #2667

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-07 14:21 UTC, victor-yanev requested changes

2024-08-07 14:21 UTC, victor-yanev commented on packages/relay/src/receiptsRootUtils.ts
> +  }
```typescript
/**
 * Represents a serialized log entry as a tuple containing:
 * - The log address as a Uint8Array.
 * - The log topics as an array of Uint8Array.
 * - The log data as a Uint8Array.
 */
type SerializedLog = [Uint8Array, Uint8Array[], Uint8Array];

export class ReceiptsRootUtils {

  /**
   * Encodes an array of logs by converting them to SerializedLog tuples.
   *
   * @param logs - The array of logs to encode.
   * @returns An array of logs encoded as `SerializedLogEntry` tuples.
   */ 
  private static encodeLogs(logs: Log[]): SerializedLogEntry[] {
    const serializedLogs: SerializedLogEntry[] = [];
    
    for (let i = 0; i < logs.length; i++) {
      const topics: Uint8Array[] = [];
      for (let j = 0; j < logs[i].topics.length; j++) {
        topics.push(hexToBytes(logs[i].topics[j]));
      }
      serializedLogs.push([hexToBytes(logs[i].address), topics, hexToBytes(logs[i].data)]);
    }

    return serializedLogs;
  }
```

2024-08-07 14:21 UTC, victor-yanev commented on packages/relay/src/receiptsRootUtils.ts
> +    ]);
This is slightly easier to follow through:
```typescript
    let receiptRoot: Uint8Array;
    if (receipt.root) {
      receiptRoot = receipt.root;
    } else if (receipt.status === 0) {
      receiptRoot = Uint8Array.from([]);
    } else {
      receiptRoot = hexToBytes('0x01');
    }
    
    const encodedReceipt = RLP.encode([
      receiptRoot,
      hexToBytes(receipt.cumulativeGasUsed),
      hexToBytes(receipt.logsBloom),
      this.encodeLogs(receipt.logs),
    ]);
```

2024-08-07 14:21 UTC, victor-yanev commented on packages/relay/src/receiptsRootUtils.ts
> +  private static encodeReceipt(receipt, txType) {
Please specify the argument types and the return type of this function

2024-08-07 14:21 UTC, victor-yanev commented on packages/relay/src/receiptsRootUtils.ts
> +  public static async getRootHash(receipts) {
Same here

2024-08-08 12:06 UTC, victor-yanev requested changes
LGTM! Few last suggestions:

2024-08-08 12:06 UTC, victor-yanev commented on packages/relay/src/receiptsRootUtils.ts
> +      await trie.put(path, this.encodeReceipt(receipt, bytesToInt(hexToBytes(receipt.type ?? EthImpl.zeroHex))));
Currently it's quite hard to follow through what these lines aim to achieve:
```suggestion
      // add a comment explaining why we are doing this check (if variable is not self-sufficient)
      const variableExplainingTheCheck = receipt.transactionIndex === EthImpl.zeroHex;
      const path = variableExplainingTheCheck
          ? RLP.encode(Buffer.alloc(0))
          : RLP.encode(bytesToInt(hexToBytes(receipt.transactionIndex ?? '')));
      const txType = bytesToInt(hexToBytes(receipt.type ?? EthImpl.zeroHex));
      const encodedReceipt = this.encodeReceipt(receipt, txType);
      await trie.put(path, encodedReceipt);
```

2024-08-08 12:06 UTC, victor-yanev commented on packages/relay/src/receiptsRootUtils.ts
> +  public static async getRootHash(receipts: ITransactionReceipt[]): Promise<string> {
nit: public methods should be on top of private methods

2024-08-14 15:32 UTC, victor-yanev submitted a review, later dismissed

2024-08-21 13:03 UTC, victor-yanev approved these changes
LGTM

**nit:** it would be nice if you could address the sonar issues about the for loop

2024-08-26 08:50 UTC, konstantinabl approved these changes

2024-08-26 08:55 UTC, victor-yanev submitted a review, later dismissed

2024-08-26 08:55 UTC, victor-yanev commented on packages/relay/src/receiptsRootUtils.ts
> +  public static buildReceiptsFromTxHashesContractResultsAndLogs(
```suggestion
  public static buildReceiptRootHashes(
```

2024-08-26 09:35 UTC, isavov submitted a review, later dismissed

2024-08-26 13:40 UTC, victor-yanev approved these changes

2024-08-26 13:41 UTC, ebadiere approved these changes
LG.

2024-08-26 13:42 UTC, merged