feat: redis cache should fallback to internal in case of error
hashgraph/hedera-json-rpc-relay pull request #2861
Opened 2024-08-21 13:05 UTC by natanasow

**Description**:

**Related issue(s)**:

Fixes #2788

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-23 13:37 UTC, victor-yanev requested changes

2024-08-23 13:37 UTC, victor-yanev commented on packages/relay/src/lib/services/cacheService/cacheService.ts
>    }
**nit:** We can avoid duplicating the fallback logic inside the `catch` and `else` blocks by adding a `return` statement if the main logic finishes successfully:

```typescript
if (this.isSharedCacheEnabled) {
  try {
     this.cacheMethodsCounter.labels(...).inc(1);
     await this.sharedCache.set(...);
     return;
  } catch {
    this.logger.error('...');
  }
}
// fallback
this.cacheMethodsCounter.labels(...).inc(1);
await this.internalCache.set(...);
```

2024-08-23 13:37 UTC, victor-yanev commented on packages/relay/src/lib/services/cacheService/cacheService.ts
> +        await this.internalCache.delete(key, callingMethod, requestIdPrefix);
**nit:** Same here

2024-08-23 13:37 UTC, victor-yanev commented on packages/relay/src/lib/services/cacheService/cacheService.ts
> +        await this.internalCache.clear();
**nit:** Same here

2024-08-23 13:37 UTC, victor-yanev commented on packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
> +      expect(await cacheService.set(key, callingMethod, undefined)).not.to.throw;
```suggestion
      await expect(cacheService.set(key, callingMethod)).to.eventually.not.be.rejected;
```

2024-08-23 13:37 UTC, victor-yanev commented on packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
> +      expect(await cacheService.delete(key, callingMethod, undefined)).not.to.throw;
```suggestion
      await expect(cacheService.delete(key, callingMethod)).to.eventually.not.be.rejected;
```

2024-08-23 13:37 UTC, victor-yanev commented on packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
> +      const cachedValue = await cacheService.getAsync(key, callingMethod, undefined);
```suggestion
      const cachedValue = await cacheService.getAsync(key, callingMethod);
```

2024-08-23 13:37 UTC, victor-yanev commented on packages/server/tests/acceptance/cacheService.spec.ts
> +    beforeEach(async () => {
Let's not slow down the tests unnecessarily:

```suggestion
    before(async () => {
```

2024-08-23 13:37 UTC, victor-yanev commented on packages/server/tests/acceptance/cacheService.spec.ts
> +    afterEach(async () => {
```suggestion
    after(async () => {
```

2024-08-26 08:56 UTC, konstantinabl approved these changes

2024-08-26 11:23 UTC, victor-yanev approved these changes

2024-08-26 13:38 UTC, merged