Updating the workflows/actions to use the step-security version.
hashgraph/hedera-json-rpc-relay pull request #2924
Opened 2024-09-02 08:32 UTC by san-est

**Description**:
Updating actions from workflows to use the step-security maintained version.

**Related issue(s)**:

Fixes #2906 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-09-04 11:49 UTC, isavov approved these changes

2024-09-04 15:12 UTC, quiet-node approved these changes

2024-09-04 17:41 UTC, rbarkerSL requested changes

2024-09-04 17:41 UTC, rbarkerSL commented on .github/workflows/dev-tool-workflow.yml
> +        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
this should be `v5.0.2`

2024-09-05 06:47 UTC, san-est commented on .github/workflows/dev-tool-workflow.yml
> +        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
I've updated it to the 5.0.2 version.

2024-09-05 15:14 UTC, rbarkerSL submitted a review, later dismissed

2024-09-12 13:08 UTC, rbarkerSL approved these changes

2024-09-18 20:50 UTC, Nana-EC approved these changes

2024-09-18 20:50 UTC, merged