ci: Updaiting workflow permissions and adding hardend runner per step-security.
hashgraph/hedera-json-rpc-relay pull request #3124
Opened 2024-10-18 12:28 UTC by san-est

**Description**:
Updating several workflows and their permissions per step-security requirements and adding hardend runner to one of the workflows.

**Related issue(s)**:

Fixes #3121 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-18 14:04 UTC, Nana-EC approved these changes

2024-10-19 03:27 UTC, rbarkerSL requested changes

2024-10-19 03:27 UTC, rbarkerSL commented on .github/workflows/pr-label-milestone-check.yml
>      runs-on: ubuntu-latest
Need to update this runner to be the self-hosted runner.

```suggestion
    runs-on: smart-contracts-linux-medium
```

2024-10-19 03:27 UTC, rbarkerSL commented on .github/workflows/conformity-workflow.yml
@Nana-EC node version 18 is end of life at the end of April 2025; can we update this to use node 20 LTS or node 22 (preferred)?

2024-10-19 03:27 UTC, rbarkerSL commented on .github/workflows/release-acceptance.yml
In the job `release-acceptance-test` the `Authenticate` step (line 31) should be modified as follows:

```suggestion
      - name: Authenticate
        env:
          HEDERA_PORTAL_USER: ${{ secrets.HEDERA_PORTAL_USER }}
          HEDERA_PORTAL_PASSWORD: ${{ secrets.HEDERA_PORTAL_PASSWORD }}
        run: |
            RESPONSE=$(jq --null-input -r --arg USER "${HEDERA_PORTAL_USER}" --arg PASS "${HEDERA_PORTAL_PASSWORD}" '{"email": $USER, "password": $PASS}' | curl -sSL -c /tmp/cookiejar.bin --data @- -X POST -H "Accept: application/json" -H "Content-Type: application/json" https://portal.hedera.com/api/session)
            echo "::add-mask::$RESPONSE"
            echo "The response was: $RESPONSE"
            ACCOUNTS_JSON="$(curl -sSL -b /tmp/cookiejar.bin -H "Accept: application/json" https://portal.hedera.com/api/account)"
            echo "::add-mask::$ACCOUNTS_JSON"
            TESTNET_ACCOUNT=$(echo $ACCOUNTS_JSON | jq -r '.accounts[] | select(.network=="testnet") | .accountNum')
            echo "The testnet account is: $TESTNET_ACCOUNT"
            PUBLIC_KEY=$(echo $ACCOUNTS_JSON | jq -r '.accounts[] | select(.network=="testnet") | .publicKey')
            echo "The publicKey is: $PUBLIC_KEY"
            PRIVATE_KEY=$(echo $ACCOUNTS_JSON | jq -r '.accounts[] | select(.network=="testnet") | .privateKey')
            echo "::add-mask::$PRIVATE_KEY"
            echo "The privateKey is: $PRIVATE_KEY"
            echo "OPERATOR_ID_MAIN=0.0.${TESTNET_ACCOUNT}" >> $GITHUB_ENV
            echo "OPERATOR_KEY_MAIN=${PRIVATE_KEY}" >> $GITHUB_ENV
```

2024-10-21 08:45 UTC, san-est commented on .github/workflows/release-acceptance.yml
Updated in latest commit.

2024-10-21 16:02 UTC, rbarkerSL approved these changes

2024-10-22 19:13 UTC, quiet-node approved these changes

2024-10-25 04:30 UTC, Nana-EC commented on .github/workflows/conformity-workflow.yml
Yes we can, but we'll do it in a separate PR.
LTS is preferred so we'll start there and see later about 22

2024-10-25 04:35 UTC, Nana-EC commented on .github/workflows/conformity-workflow.yml
Captured this here - https://github.com/hashgraph/hedera-json-rpc-relay/issues/3156

2024-10-25 04:36 UTC, Nana-EC commented
@san-est need to fix DCO then you can check in

2024-10-29 10:51 UTC, merged