feat: Adds draft design doc for new block explorer REST API endpoints
hashgraph/hedera-json-rpc-relay pull request #3342
Opened 2024-12-18 17:39 UTC by konstantinabl

**Description**:

Creates a design document for the new block explorer REST API endpoints

**Related issue(s)**:

Fixes #3340 

**Notes for reviewer**:

2024-12-20 00:02 UTC, Nana-EC reviewed
Good start.
I think we have to think through the way in which this would deploy and scale a bit more.

2024-12-20 00:02 UTC, Nana-EC commented on docs/design/additional-endpoints.md
> +- ERC registry
How so, please expand

2024-12-20 00:03 UTC, Nana-EC requested changes
Good start waiting on a bit more structure

2025-01-06 22:25 UTC, quiet-node reviewed
Great process! Many questions and suggestions

2025-01-06 22:25 UTC, quiet-node commented on docs/design/additional-endpoints.md
> +- `standard`: The token standard to filter by
Also, since these are RESTful, having an example of parameters within the endpoints, similar to what Etherscan provides, would be clear and helpful.

<img width="797" alt="image" src="https://github.com/user-attachments/assets/5c42c2e8-d123-4a9a-8fdc-ba4068df0c54" />

2025-01-07 14:20 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +- `getTokenTransfers` - to fetch token transfer events
So i think in the overview its enough to state the format of the endpoint and the detailed explanation down where it is, do you think thats fine or should I move it all to this section? 
Also I have chosen this classic REST format, which differentiates from the way etherscan and blockscout has implemented their endpoints, entirely with query parameters, not sure if thats gonna affect the user. Do they expect the exactly same format
In etherscan the ednpoints look like this:
```
GET /api
   ?module=account
   &action=tokentx
   &contractaddress=0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2
   &address=0x4e83362442b8d1bec281594cea3050c8eb01311c
   &page=1
   &offset=100
   &startblock=0
   &endblock=27025780
   &sort=asc
   &apikey=YourApiKeyToken
```

2025-01-07 16:17 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +- `standard`: The token standard to filter by
> Would these parameters be sufficient to determine if a request is looking for ERC20, ERC721, or ERC1155? In the example from Etherscan, they use `action=tokentx|tokennfttx|token1155tx`. I’m not suggesting we should follow their approach, but would a similar parameter be useful?
@quiet-node I was thinking that the standard token will provide information if the user wants erc20/erc721 or erc1155 info

2025-01-07 17:40 UTC, quiet-node commented on docs/design/additional-endpoints.md
> +- `standard`: The token standard to filter by
What do you mean by “standard token”?

Are you suggesting that the service class would be designed to identify whether a token is ERC20 or ERC721 (e.g., through interface signature matching) based on its token address? If so, this might not be a straightforward task. The process could involve making a call to the MN to retrieve the contract’s bytecode using the token address and then performing interface signature matching, similar to the approach used in the ERC-registry project.

However, this method could introduce some overhead. To mitigate this, allowing users to provide a flag, as EtherScan does, might be a more efficient solution, saving both time and some computational resources.

2025-01-07 20:27 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +3. Consider the amount of resources required to check the ERC registry for each log
its not relevant I deleted it

2025-01-07 20:28 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +The `getTokenTransfers` endpoint will be calling the same method in the `EthImpl` class which will accept the following parameters:
I removed this section, since I reworked the design doc a little bit

2025-01-07 20:36 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +- `standard`: The token standard to filter by
Sorry logan, that was a typo. What i meant is that we will determine what type of token the request is looking for via the token parameter. 
As for the rest of your other comment, I was planning on using the erc registry to check if a contactId is associated to a erc20 and erc721. For 1155 I wanted to have a dsicussion. Hope I answered your question : )

2025-01-07 20:38 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +2. **Acceptance Tests**
Edited them : )

2025-01-07 20:40 UTC, quiet-node commented on docs/design/additional-endpoints.md
> +- `standard`: The token standard to filter by
Ohhh it makes sense! And sorry I completely missed the standard, yeah I think it's sufficient enough! Thanks for pointing it out!

2025-01-07 21:06 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +### Components
Reformed the design doc so we implement this as a new package

2025-01-07 21:07 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +```
Since this will be a standalone package i reformed the design doc and this is not relevant anymore

2025-01-08 05:36 UTC, Nana-EC reviewed
Great start, looking forward to discussing more

2025-01-08 05:36 UTC, Nana-EC commented on docs/design/additional-endpoints.md
> +- Caches frequent queries
Can we call out the cached objects. I'd like to ensure that we only cache what is needed e.g. in some cases the relay caches the full account or token object but we really only need a few fields from the mirror node response.
In this case do we need to cache a full log or can we cache only a subset of them?

2025-01-08 05:36 UTC, Nana-EC commented on docs/design/additional-endpoints.md
> +- Caches frequent queries
Please suggest an TTL for these caches components.

2025-01-08 05:36 UTC, Nana-EC commented on docs/design/additional-endpoints.md
> +1. Possibly restrict the number of logs returned by the MN to a maximum of 10000
We currently have a max on the logs endpoint we can likely match that

2025-01-08 05:36 UTC, Nana-EC commented on docs/design/additional-endpoints.md
> +         ├── config/           # Configuration for REST API
I don't see a section for this, could you add one that calls out which config fields you plan to add and what their defaults might be?

2025-01-08 05:36 UTC, Nana-EC commented on docs/design/additional-endpoints.md
> +   rest-api/
Hmm, another approach would be `rest-server` package with the controllers under there and the services under the `relay` package or this new `rest-api` package.
In this way the service implementation could be change in the future a transparent way or the underlying server logic - both packages decoupled from each other.
Let's chat about it, the above is food for thought and might hint towards the final form we want to get to in a tentative refactor of the repo

2025-01-08 05:36 UTC, Nana-EC commented on docs/design/additional-endpoints.md
> +* ERC registry - As explained in the _Flow_ section, the TokenService will need to fetch the ERC registry to get the token standard (ERC20/721/ 1155) contracts and filter the response by only those m
You should note that initially we'll use the static outputs from the smart contract repo. We should be able to import that package soon but int eh early stage we can copy over the files as needed

2025-01-08 13:53 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +* ERC registry - As explained in the _Flow_ section, the TokenService will need to fetch the ERC registry to get the token standard (ERC20/721/ 1155) contracts and filter the response by only those m
changed

2025-01-10 14:52 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +- Caches frequent queries
No, we dont need to cache the full object, so I changed and specified what we will need

2025-01-10 16:06 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +- Caches frequent queries
Done

2025-01-10 16:06 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +1. Possibly restrict the number of logs returned by the MN to a maximum of 10000
Currently, investigating this. Seems liek tis 25, but thats too low for our purposes @Nana-EC

2025-01-13 04:45 UTC, Nana-EC reviewed
Good suggestions @konstantinabl.
To confirm after some thought we should indeed position this from the get go as an independently deployable instance.
Should be something like `http-explorer-server` containing the specific etherscan focused controllers and server logic.
Initially we can colocate the api logic including services  in the `relay` package then revisit when we pick up the repo refactor

2025-01-13 13:25 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +| `GET /api?module=account&action=tokentx&address={address}&contractaddress={contractaddress}&startblock={startblock}&endblock={endblock}&page={page}&offset={offset}&sort={asc\|desc}` | Get ERC20 tok
@Nana-EC I get what you mean, but I think their design is like this because they have different networks available. And will we have something else than etherscan, imo it may be confusing to have it like this, since we may also want to redesign the endpoint format in the future.

2025-01-13 13:53 UTC, Nana-EC commented on docs/design/additional-endpoints.md
> +| `GET /api?module=account&action=tokentx&address={address}&contractaddress={contractaddress}&startblock={startblock}&endblock={endblock}&page={page}&offset={offset}&sort={asc\|desc}` | Get ERC20 tok
That's why having a unique oath would be preferred. I that way the etherscan support approach can be left alone and a future version that we designed with better REST principles could be added with my conflict

2025-01-13 17:02 UTC, quiet-node reviewed
Great work! Love how meticulous this design doc is! Left comments and quetions around

2025-01-13 17:44 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +*  No API key for authorization
Good catch! Fixing it

2025-01-13 17:57 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +| standard | The token standard to filter by (ERC20/721/1155) | Yes | - |
Removed

2025-01-13 18:17 UTC, quiet-node approved these changes
LGTM

2025-01-13 18:32 UTC, Ferparishuertas reviewed
Nice job. I left some comments

2025-01-13 19:55 UTC, acuarica commented on docs/design/additional-endpoints.md
> +## Goals
No, the verification service is the source of truth when getting the ABI.

2025-01-14 09:32 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +   - Rate limiting
What I mean here is reate limiting of the endpoints as in json-rpc. Since these new endpoints will be in a separate package, they will need rate limiting as done for the json rpc ones in the server package

2025-01-14 09:33 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +### Testing Requirements
This is quite a good idea, however we usually don't implement such tests, we may discuss in the daily though. I dont mind including it if we agree

2025-01-14 09:47 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +2. Possibly restrict the block range to a maximum of 10000 blocks
Not quite sure what you mean. In etherscan 10000 records limit is for [this endpoint](https://docs.etherscan.io/api-endpoints/accounts#get-internal-transactions-by-block-range), which we are not going to implement. The limit i mentioned here is for this one, 
https://docs.blockscout.com/devs/apis/rpc/account#get-token-transfer-events-by-address, where they have limit for 10000 blocks

2025-01-14 15:01 UTC, konstantinabl commented on docs/design/additional-endpoints.md
> +#### 1. TokenController
I name it token controller, since I plan it will be responsible for all the endpoints from the token module but i may put it into etherscan folder

2025-01-14 15:27 UTC, Ferparishuertas commented on docs/design/additional-endpoints.md
> +### Testing Requirements
Understood. Lets keep this , and discuss after the sprint, the usual testing piramid, for my personal knowledge :)

2025-01-14 15:34 UTC, Ferparishuertas commented on docs/design/additional-endpoints.md
> +#### 1. TokenController
Imagine we implement etherscan and snowflake. Same controlles for both, or separated ( folder/ naming)? what will the approach?
Personally Iam used to split to find easierm group things. Whats the usual approach here?

2025-01-28 13:16 UTC, closed without merging

2025-01-28 13:16 UTC, konstantinabl commented
Irrelevant since we went with another approach for blockscout