Web3js <> relay compatibility
hashgraph/hedera-json-rpc-relay pull request #370
Opened 2022-07-22 10:35 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #313

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-07-22 19:03 UTC, Nana-EC requested changes
Looking good.
Split github action out and update license

2022-07-22 19:03 UTC, Nana-EC commented on tools/web3js-example/package.json
> +  "license": "ISC",
All licenses should be Apache 2.0

2022-07-23 22:47 UTC, Nana-EC approved these changes
LG
2 nits if you circle back

2022-07-23 22:47 UTC, Nana-EC commented on tools/web3js-example/scripts/deployContract.js
> +    arguments: ['initial_msg']
nit: make this a pass in param since it's used in rpc.js

2022-07-23 22:47 UTC, Nana-EC commented on tools/web3js-example/test/rpc.js
> +    const res = await contractViewCall(contractAddress);
pass in init message
```suggestion
    const msg = 'initial_msg';
    const res = await contractViewCall(contractAddress, msg);
```

2022-07-25 06:36 UTC, Daniel-K-Ivanov approved these changes
LGTM!

2022-07-25 06:38 UTC, merged