add specific error classes for SDKClient and MirrorNodeCLient
hashgraph/hedera-json-rpc-relay pull request #382
Opened 2022-07-25 22:15 UTC by lukelee-sl

Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>

**Description**:
Create error classes for SDKClient and MirrorNodeClient classes.

**Related issue(s)**:

Fixes #213 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-07-26 05:30 UTC, ar-conmit submitted a review, later dismissed
LG

2022-07-26 07:04 UTC, Nana-EC requested changes
Nice start.
Let's move some of the logic into the error class files

2022-07-26 07:04 UTC, Nana-EC commented on packages/relay/src/lib/errors.ts
> +    this.name = "SDKClientError";
Not sure this is needed since it's implied by the type.

2022-07-26 21:47 UTC, Nana-EC requested changes
Almost there. 1 modification 2 nits

2022-07-26 21:47 UTC, Nana-EC commented on packages/relay/src/lib/errors/JsonRpcError.ts
> +};
restore new line.
Make git diff easier

2022-07-26 21:47 UTC, Nana-EC commented on packages/relay/src/lib/errors/MirrorNodeClientError.ts
> +  }
nit: new line

2022-07-26 21:47 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
> +        throw e;
All returns should be of predefined types where possible
```suggestion
        return predefined.INTERNAL_ERROR;        
```

2022-07-27 03:56 UTC, Nana-EC approved these changes

2022-07-27 04:52 UTC, merged