Calls with bad data should return an error response
hashgraph/hedera-json-rpc-relay pull request #390
Opened 2022-07-28 08:27 UTC by natanasow

**Description**:

**Related issue(s)**:

Fixes #385

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-07-28 09:14 UTC, ar-conmit submitted a review, later dismissed
LGTM

2022-07-29 00:47 UTC, Nana-EC requested changes
Missing test.

2022-07-29 00:47 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
> +      throw predefined.INTERNAL_ERROR;
There should be an `eth.spect.ts` test to highlight the issue the bug highlighted

2022-07-29 08:51 UTC, Ivo-Yankov approved these changes

2022-07-29 17:22 UTC, Nana-EC approved these changes
LGTM

2022-07-30 02:28 UTC, merged