Add htsPreCompile get tokenInfo acceptance tests
hashgraph/hedera-json-rpc-relay pull request #450
Opened 2022-08-17 12:26 UTC by ar-conmit

**Description**:
Add tests for:
* getFungibleTokenInfo
* getTokenInfo
* getNonFungibleTokenInfo - depends on `mintToken`
* mintToken

**Related issue(s)**:

Fixes #400 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-08-17 15:44 UTC, Nana-EC requested changes
LG, just some missing property coverage

2022-08-17 15:44 UTC, Nana-EC commented on packages/server/tests/acceptance/htsPrecompile.spec.ts
> +    expect(token.symbol).to.equal(TOKEN_SYMBOL);
Add coverage for decimal also

2022-08-17 15:44 UTC, Nana-EC commented on packages/server/tests/acceptance/htsPrecompile.spec.ts
> +    expect(token.symbol).to.equal(TOKEN_SYMBOL);
Add coverage for serial number

2022-08-18 06:27 UTC, ar-conmit commented on packages/server/tests/acceptance/htsPrecompile.spec.ts
> +    expect(token.symbol).to.equal(TOKEN_SYMBOL);
Done

2022-08-18 06:27 UTC, ar-conmit commented on packages/server/tests/acceptance/htsPrecompile.spec.ts
> +    expect(token.symbol).to.equal(TOKEN_SYMBOL);
Done

2022-08-18 14:32 UTC, Nana-EC approved these changes
LGTM

2022-08-18 14:34 UTC, merged