Add HtsPrecompile test support for getTokenCustomFees
hashgraph/hedera-json-rpc-relay pull request #452
Opened 2022-08-18 13:55 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #406

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-08-18 20:17 UTC, Nana-EC requested changes
LG, merge tests and rebase

2022-08-18 20:17 UTC, Nana-EC commented on packages/server/tests/acceptance/htsPrecompile.spec.ts
> +    HTSTokenWithCustomFeesContractAddress = tokenAddress;
Move this to the `beforeAll` if you want all tests to have access to this contract.
Or combine the 2 tests, create and get.

2022-08-18 23:51 UTC, shemnon submitted a review, later dismissed

2022-08-19 19:54 UTC, shemnon submitted a review, later dismissed

2022-08-19 22:07 UTC, Nana-EC approved these changes
LG

2022-08-22 09:47 UTC, Ivo-Yankov approved these changes

2022-08-22 10:19 UTC, merged