Describe the invalid precomputed address issue in the tools readme
hashgraph/hedera-json-rpc-relay pull request #458
Opened 2022-08-19 13:32 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #193

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-08-19 22:21 UTC, Nana-EC requested changes
Looking good.
Some documentation suggestions

2022-08-19 22:21 UTC, Nana-EC commented on tools/README.md
> +#### Option 1
Please update the X mark in the table to a yellow caution/exclamation.

2022-08-19 22:21 UTC, Nana-EC commented on tools/README.md
> +
Update the Note:" to add
"[ethers js](https://docs.ethers.io/v5/api/utils/address/#utils--contract-addresses) and therefore Hardhat usage are impacted by this address calculation difference with the details captured [here](https://github.com/ethers-io/ethers.js/discussions/3141).
An extra step to retrieve the valid Hedera contract address is required to workaround this challenge, example workarounds are provided below"

2022-08-19 22:21 UTC, Nana-EC commented on tools/README.md
> +// wait till the transaction is mined and get the contract address from the receipt
```suggestion
// wait till the transaction has reached consensus and get the contract address from the receipt
```

2022-08-19 22:21 UTC, Nana-EC commented on tools/README.md
> +// wait for transaction to be mined
```suggestion
// wait for transaction to reach consensus 
```

2022-08-22 17:11 UTC, Nana-EC submitted a review, later dismissed
You forget to add the link to the discussion item.
Rest looks good. Signing off so I'm not blocking once you make that change since the rest is good

2022-08-22 17:11 UTC, Nana-EC commented on tools/README.md
> +
You didn't add the link to the discussion item on the etherejs repo for the "here"

2022-08-23 07:58 UTC, Ivo-Yankov approved these changes

2022-08-23 07:59 UTC, merged