Add HTS Precompile tests for token check methods
hashgraph/hedera-json-rpc-relay pull request #468
Opened 2022-08-24 11:46 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-08-24 16:55 UTC, Nana-EC requested changes
Looks good.
Some clarifying suggestions.

Once addressed please move PR to draft.
Let's wait on services tag before checking this PR in.

2022-08-24 16:55 UTC, Nana-EC commented on packages/server/tests/acceptance/htsPrecompile.spec.ts
> +    it('should returns 1 for getTokenType with passed HTS nft token', async function() {
```suggestion
    it('should return 1 for getTokenType with passed HTS nft token', async function() {
```

2022-08-24 16:55 UTC, Nana-EC commented on packages/server/tests/acceptance/htsPrecompile.spec.ts
> +    it('should returns 0 for getTokenType with passed HTS token', async function() {
```suggestion
    it('should returns 0 for getTokenType with passed FUNGIBLE_COMMON token', async function() {
```

2022-08-24 16:55 UTC, Nana-EC commented on packages/server/tests/acceptance/htsPrecompile.spec.ts
> +    it('should returns 1 for getTokenType with passed HTS nft token', async function() {
```suggestion
    it('should returns 1 for getTokenType with passed HTS NON_FUNGIBLE_UNIQUE token', async function() {
```

2022-09-14 17:14 UTC, Nana-EC submitted a review, later dismissed
LG, please update PR description to match your changes

2022-09-15 09:33 UTC, Ivo-Yankov approved these changes

2022-09-15 14:33 UTC, merged