Add env variable to control rate limiting
hashgraph/hedera-json-rpc-relay pull request #655
Opened 2022-10-26 09:06 UTC by Ivo-Yankov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-10-27 00:32 UTC, Nana-EC requested changes
LG, needs chart updating also

2022-10-27 00:32 UTC, Nana-EC commented on .env.example
> +RATE_LIMIT_DISABLED =
Update the Helm chart also
See https://github.com/hashgraph/hedera-json-rpc-relay/pull/578/files as a reference

2022-10-27 16:49 UTC, Nana-EC approved these changes
LG

2022-10-27 17:28 UTC, georgi-l95 approved these changes

2022-10-27 17:58 UTC, georgi-l95 requested changes
Just need to add this new variable to the [README.md](https://github.com/hashgraph/hedera-json-rpc-relay#testing)

2022-10-28 07:47 UTC, georgi-l95 approved these changes
LG

2022-10-28 08:25 UTC, merged