Add config support for SDK transport security
hashgraph/hedera-json-rpc-relay pull request #741
Opened 2022-12-05 12:42 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #727

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-12-05 16:30 UTC, Nana-EC requested changes
Looking good
Please update PR comments with something like
`Update relay.ts to set transport based on value of new CLIENT_TRANSPORT_SECURITY config`

Additionally, you need to expose this in the Helm charts `values.yaml` and `deployment.yaml` so it can be utilized

2022-12-06 17:29 UTC, Nana-EC commented on helm-chart/templates/deployment.yaml
> +                optional: false
```suggestion
                optional: true
```

2022-12-06 20:14 UTC, georgi-l95 commented on helm-chart/templates/deployment.yaml
> +                optional: false
Done.

2022-12-07 00:02 UTC, Nana-EC approved these changes
LG

2022-12-07 07:56 UTC, merged