Pad slot value on comparison
hashgraph/hedera-json-rpc-relay pull request #770
Opened 2022-12-14 14:38 UTC by natanasow

Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #769

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-12-14 14:58 UTC, dimitrovmaksim commented on packages/relay/src/lib/eth.ts
> +    return input.length === 66 ? input : EthImpl.emptyHex + this.prune0x(input).padStart(64, '0');
Instead of hardcoding `64` here I would go with `64 - this.prune0x(input).length`

2022-12-14 15:10 UTC, dimitrovmaksim commented on packages/relay/src/lib/eth.ts
> +    return input.length === 66 ? input : EthImpl.emptyHex + this.prune0x(input).padStart(64, '0');
Yeah you're right, sorry, I misunderstood `padStart`

2022-12-14 15:30 UTC, Nana-EC requested changes
Missing coverage

2022-12-14 15:30 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
> +            if (stateChange) {
Update `eth.spec.ts` with coverage for result setting and different paths within `toHex32Byte()`

2022-12-15 10:55 UTC, georgi-l95 submitted a review, later dismissed
LGTM

2022-12-16 00:35 UTC, Nana-EC submitted a review, later dismissed

2022-12-16 15:21 UTC, lukelee-sl submitted a review, later dismissed
LGTM

2022-12-17 09:49 UTC, Nana-EC submitted a review, later dismissed

2022-12-18 08:22 UTC, dimitrovmaksim commented
I think the mirror-node images should be updated to 0.70.0 in order for the getStorageAt test to pass, because 0.69.0 does not include this PR https://github.com/hashgraph/hedera-mirror-node/pull/4881

2022-12-19 10:44 UTC, georgi-l95 approved these changes
LGTM

2022-12-19 10:47 UTC, dimitrovmaksim approved these changes

2022-12-19 11:00 UTC, merged