Caching improvements
hashgraph/hedera-json-rpc-relay pull request #931
Opened 2023-02-21 11:17 UTC by natanasow

**Description**:

**Related issue(s)**:

Fixes #915 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-02-22 00:29 UTC, Nana-EC requested changes
looking good, missing test cases to verify these 2 caches are hit

2023-02-22 00:29 UTC, Nana-EC commented on packages/relay/src/lib/eth.ts
> +      let toAccount: object | null = this.cache.get(accountCacheKey);
This is a cache addition not an improvement.
Please update the PR description with the goal and changes here

2023-02-23 01:00 UTC, Nana-EC approved these changes

2023-02-23 08:05 UTC, georgi-l95 approved these changes
LGTM

2023-02-23 08:13 UTC, merged